export const surpriseMePrompts = [
    'A giant snail wearing a city skyline as its shell, digital art',
    'A steampunk robot sipping tea in a Victorian-era living room',
    'An owl reading a book under a glowing mushroom in a magical forest, fantasy art',
    'A cyberpunk cityscape reflected in the eyes of a futuristic android, digital art',
    'A hot air balloon made of jellyfish floating over an alien ocean, surreal',
    'A neon-lit vending machine that dispenses galaxies, digital art',
    'A watercolor painting of a whimsical tea party hosted by foxes and rabbits in a snowy forest',
    'A futuristic train speeding through a tunnel of stars, digital art',
    'A golden retriever playing poker with a group of raccoons in a cozy cabin, cartoon style',
    'A superhero sloth soaring through the clouds, comic book style',
    'A whimsical clock tower that appears to be melting like Salvador Dalí’s “Persistence of Memory”',
    'A robot gardener tending to bioluminescent plants on the surface of the Moon',
    'A bustling marketplace in an underwater city, populated by mermaids and sea creatures',
    'A 3D render of a cupcake shaped like a galaxy with edible planets and stars',
    'A dragon lounging in a modern-day apartment, surrounded by piles of gold and pizza boxes',
    'An isometric view of a floating city made of glass and clouds',
    'A medieval knight riding a bicycle through a field of sunflowers, oil painting style',
    'A tiny, cozy library inside a hollowed-out tree, illuminated by fireflies',
    'A photograph of a UFO landing in a sunflower field at dusk',
    'A penguin in a tuxedo walking down the red carpet at an alien awards show',
    'A futuristic spacecraft shaped like a seashell floating above a tropical island, digital art',
    'A glowing jellyfish chandelier in an underwater palace, fantasy art',
    'A time traveler having coffee with a dinosaur in a retro diner',
    'A cat dressed as a wizard casting a spell in a room full of floating books',
    'A squirrel wearing a spacesuit exploring an alien jungle, digital art',
    'A floating castle made of candy surrounded by a rainbow sky, fantasy art',
    'A Viking ship sailing through a sea of clouds, surrealism',
    'A futuristic library with bookshelves that float in mid-air, digital art',
    'A cat playing a grand piano on a stage lit by moonlight, oil painting',
    'A 3D render of a crystal dragon perched on a glowing mountain',
    'A coffee cup that looks like it’s made of swirling galaxies, digital art',
    'A family of penguins having a picnic on a tropical beach, whimsical style',
    'A robot painter creating a masterpiece on a canvas in a dystopian city',
    'A deer made of flowers standing in the middle of an enchanted forest, watercolor',
    'A fox wearing a detective hat and investigating a crime scene in a dark alley, noir style',
    'A futuristic train station where passengers are robots and aliens, sci-fi art',
    'A donut-shaped spaceship orbiting a planet made of frosting, cartoon art',
    'A magical school floating on a giant turtle’s back, fantasy art',
    'An astronaut fishing for stars in the Milky Way, digital painting',
    'A tea set shaped like mushrooms in a whimsical forest setting',
    'A snowman enjoying a tropical vacation under a palm tree, surrealism',
    'A futuristic city with buildings shaped like trees, eco-friendly architecture',
    'A neon-colored koi fish swimming in the night sky, fantasy art',
    'A panda meditating on top of a glowing lotus flower, zen art',
    'A photograph of a robot chef cooking gourmet meals in a high-tech kitchen',
    'A roller coaster built on the rings of Saturn, digital art',
    'A polar bear and a penguin flying a hot air balloon over a frozen landscape',
    'A whimsical map of a treasure island shaped like a dragon, fantasy illustration',
    'A steampunk airship docked at a floating island in the clouds, digital art',
    'A majestic phoenix made entirely of glowing lava, emerging from a volcano',
    'A mouse knight wielding a needle sword, defending a cheese kingdom',
    'A futuristic marketplace on Mars filled with alien traders, sci-fi art',
    'A whimsical scene of a snail riding a unicycle through a garden, cartoon style',
    'A time-traveling scientist observing dinosaurs through futuristic binoculars',
    'A hot cup of coffee with steam forming the shape of a magical dragon, digital art',
    'A rainbow bridge connecting two floating islands in a sunset-lit sky',
    'A cozy cabin on the back of a giant tortoise walking through a misty forest',
    'A giraffe wearing sunglasses and riding a skateboard in a city park, cartoon style',
    'A futuristic diner on the edge of a black hole, serving glowing food, sci-fi art',
    'A treehouse village built into a massive ancient oak tree, fantasy illustration',
    'A dog piloting a biplane through a sky filled with floating jellyfish, whimsical style',
    'A mermaid conducting an underwater orchestra of sea creatures, digital art',
    'A robot bartender serving neon-colored drinks in a cyberpunk bar',
    'A tiger relaxing on a hammock in a jungle, sipping coconut water, oil painting',
    'A spaceship shaped like a teapot flying through a galaxy of stars, surrealism',
    'A glowing phoenix rising from the ashes in a snowy mountain landscape, fantasy art',
    'A parade of animals wearing royal attire walking through a forest, watercolor',
    'A mushroom village lit by bioluminescent fireflies in a dark forest, fantasy art',
    'A steam-powered mechanical elephant walking through a bustling Victorian street',
    'A raccoon stealing snacks from a vending machine at night, cartoon style',
    'A magical bridge made of ice and light connecting two snowy peaks, fantasy art',
    'A dragon sleeping peacefully in a bed of glowing crystals in a cave, digital art',
    'A futuristic skyline with holographic billboards and flying cars, sci-fi art',
    'A polar bear and a seal having tea in an igloo, surrounded by glowing ice sculptures',
    'A giant octopus playing a piano underwater in a coral reef, surreal art',
    'A flying bookstore powered by hot air balloons, floating over a green valley',
    'A whimsical scene of a hedgehog riding a bicycle through a sunflower field',
    'A neon-colored cyberpunk samurai standing on a rainy rooftop, sci-fi art',
    'A wolf howling at a glowing moon that looks like a disco ball, fantasy style',
    'A 3D render of a futuristic garden with robotic bees pollinating metal flowers',
    'A realistic photo of an alien family having a picnic under two suns',
    'A chessboard where the pieces are alive and interacting like humans, surreal art',
    'A fairy-tale castle on top of a floating iceberg drifting through the sky',
    'A koi pond in space where the fish are made of stardust, digital art',
    'A mysterious hooded figure walking through a glowing forest of crystal trees',
    'A carnival run entirely by robots with glowing Ferris wheels and rides',
    'A submarine shaped like a whale exploring a sunken pirate ship, digital art',
    'A steampunk watchmaker crafting a clock with glowing gears, fantasy illustration',
    'A desert landscape with a caravan of camels carrying futuristic technology',
    'A whimsical bakery where all the cakes and pastries are shaped like animals',
    'A massive aquarium in a futuristic city where people walk on glass bridges above it',
    'A panda wearing a detective coat and solving mysteries in a foggy city, noir style',
    'A city built entirely on the backs of giant turtles swimming in an endless ocean',
    'A robot dog herding glowing sheep on a futuristic farm, sci-fi art',
    'A magical floating island with waterfalls cascading into the clouds below',
    'A steampunk airship shaped like a whale flying over a bustling metropolis',
    'A frog prince sitting on a throne made of lily pads, surrounded by glowing fireflies',
    'A train station in the middle of a desert, but the trains are futuristic hovercrafts',
    'A neon jellyfish swimming through the streets of a cyberpunk city, digital art',
    'A cat café on Mars with aliens and robots as customers, whimsical illustration',
    'A snowy owl delivering glowing letters in a moonlit forest, fantasy style',
    'A dragon curled up inside a library, reading ancient scrolls by candlelight',
    'A carousel with unicorns and pegasus rides in the middle of a starlit sky',
    'A cozy cabin with smoke forming the shape of animals rising from the chimney',
    'A futuristic city where trees are buildings, and people live in the branches',
    'A lighthouse floating on a tiny asteroid in the middle of space, surreal art',
    'A wolf wearing a crown howling on a glowing crystal cliff under the aurora borealis',
    'A vending machine that dispenses dreams, glowing in a dark alleyway',
    'A 3D render of a turtle with a garden growing on its shell, swimming in a clear ocean',
    'A magical ship sailing on a river of stars through a dreamy galaxy',
    'A futuristic subway station glowing with holographic maps and alien passengers',
    'A neon-colored desert with glowing cacti and a cyberpunk cowboy riding a robotic horse',
    'A robot orchestra performing a concert in a grand futuristic opera house',
    'A fox wearing a monocle and top hat reading a newspaper in a Victorian café',
    'A realistic photo of a waterfall flowing upwards into the sky, surrounded by lush forest',
    'A giant snail carrying a futuristic city on its back, traveling through a desert',
    'A fairy blowing bubbles that turn into tiny planets, fantasy art',
    'A hot chocolate cup with marshmallows shaped like stars floating in glowing liquid',
    'A giraffe with a telescope observing constellations from a floating observatory',
    'A moonlit village where the houses are shaped like mushrooms and pumpkins',
    'A futuristic skatepark where hoverboards leave glowing trails in the night sky',
    'A black cat walking on a piano in a candle-lit room, creating magical music notes',
    'A cosmic dragon flying through a nebula filled with glowing stars, digital art',
    'A glowing spiral staircase floating in the middle of a serene, endless ocean',
    'A cozy campsite on the rings of Saturn, with glowing tents and a starry sky'
];
